from django.urls import path

from . import views


app_name = "main"


urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "gaming-rooms/",
        views.gaming_rooms,
        name="gaming_rooms",
    ),
    path(
        "gaming-rooms/<slug:slug>/",
        views.gaming_room_detail,
        name="gaming_room_detail",
    ),
    path(
        "register/",
        views.register_view,
        name="register",
    ),
    path(
        "login/",
        views.login_view,
        name="login",
    ),
    path(
        "logout/",
        views.logout_view,
        name="logout",
    ),
    path(
        "profile/",
        views.profile_view,
        name="profile",
    ),
    path(
        "profile/edit/",
        views.profile_edit,
        name="profile_edit",
    ),
    path(
        "profile/password/",
        views.change_password,
        name="change_password",
    ),
    path(
        "booking/create/<slug:slug>/",
        views.booking_create,
        name="booking_create",
    ),
    path(
        "booking/<int:booking_id>/",
        views.booking_detail,
        name="booking_detail",
    ),
    path(
        "booking/create/<slug:slug>/confirm/",
        views.booking_confirm,
        name="booking_confirm",
    ),
    path(
        "booking/<int:booking_id>/cancel/",
        views.booking_cancel,
        name="booking_cancel",
    ),
    path(
        "booking/<int:booking_id>/payment/",
        views.payment_create,
        name="payment_create",
    ),
    path(
        "payment/<int:payment_id>/",
        views.payment_detail,
        name="payment_detail",
    ),
    path(
        "gaming-rooms/<slug:slug>/review/",
        views.review_create,
        name="review_create",
    ),
    path(
        "review/<int:review_id>/edit/",
        views.review_edit,
        name="review_edit",
    ),
    path(
        "review/<int:review_id>/delete/",
        views.review_delete,
        name="review_delete",
    ),
    path(
        "gaming-rooms/<slug:slug>/favorite/",
        views.favorite_toggle,
        name="favorite_toggle",
    ),
    path(
        "favorites/",
        views.favorites,
        name="favorites",
    ),
    path(
        "chat/",
        views.chat,
        name="chat",
    ),
    path(
        "chat/<int:user_id>/",
        views.chat_with_user,
        name="chat_with_user",
    ),
    path(
        "chat/<int:user_id>/send/",
        views.send_message,
        name="send_message",
    ),
    path(
        "chat/message/<int:message_id>/read/",
        views.mark_message_read,
        name="mark_message_read",
    ),
    path(
        "game/",
        views.game,
        name="game",
    ),
    path(
        "game/score/",
        views.save_game_score,
        name="save_game_score",
    ),
    path(
        "leaderboard/",
        views.leaderboard,
        name="leaderboard",
    ),
]