# Generated by Django 5.2.17 on 2026-08-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gaming_rooms/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_players', models.PositiveIntegerField()),
                ('room_number', models.PositiveIntegerField()),
                ('tv_size', models.PositiveIntegerField(help_text='TV size in inches')),
                ('supports_4k', models.BooleanField(default=True)),
                ('supports_hdr', models.BooleanField(default=True)),
                ('ps5_pro', models.BooleanField(default=True)),
                ('vr_available', models.BooleanField(default=False)),
                ('controllers', models.PositiveIntegerField(default=2)),
                ('internet_speed', models.CharField(default='1 Gbps', max_length=50)),
                ('rgb_lighting', models.BooleanField(default=True)),
                ('air_conditioner', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaming_rooms', to='main.category')),
                ('games', models.ManyToManyField(related_name='gaming_rooms', to='main.game')),
            ],
            options={
                'verbose_name': 'Gaming Room',
                'verbose_name_plural': 'Gaming Rooms',
                'ordering': ['title'],
            },
        ),
    ]
