# Generated by Django 5.2.17 on 2026-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_booking_unique_room_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Simulation', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed')], default='waiting', max_length=20),
        ),
    ]
