# Generated by Django 5.2.17 on 2026-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_city_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed')], default='waiting', max_length=20),
        ),
    ]
